  logsBucket: 'gs://finale_logs'
  
  steps:
  # running docker-compose
  - name: 'docker/compose:1.29.2'
    args: ['up', '-d']
  
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['build', '-t', 'gcr.io/cloudrun/placeholder', '.']

options:
  logging: CLOUD_LOGGING_ONLY
